#include "maze/MazeDesign.hpp"

namespace maze
{

const std::vector<uint8_t> MazeDesign::MAZE_1(
{
    NXXW, NEXX, NXXW, NEXX, XXSW, NXSX, NEXX, NXXW, NXSX, NEXX,
    XEXW, XXSW, XESX, XEXW, NXXW, NXSX, XESX, XXSW, NEXX, XESW,
    XEXW, NEXW, NXXW, XESX, XEXW, NXXW, NXSX, NEXX, XXSW, NEXX,
    XXXW, XESX, XXSW, NXSX, XESX, XESW, NXXW, XXSX, NXSX, XEXX,
    XEXW, NXSW, NEXX, NEXW, NXXW, NEXX, XEXW, NEXW, NXXW, XEXX,
    XXSW, NEXX, XXXW, XEXX, XXSW, XEXX, XXSW, XESX, XEXW, XEXW,
    NXXW, XESX, XESW, XEXW, NXXW, XEXX, NXXW, NXXX, XESX, XESW,
    XXXW, NXSX, NEXX, XXSW, XESX, XEXW, XEXW, XXSW, NXSX, NEXX,
    XXSW, NEXX, XXSW, NXXX, NESX, XEXW, XEXW, NXXW, NESX, XEXW,
    NXSW, XESX, NXSW, XXSX, NXSX, XXSX, XESX, XXSW, NXSX, XESX
});

}
